/*
 * This file is generated by jOOQ.
 */
package com.cockroachlabs.example.jooq.db;


import com.cockroachlabs.example.jooq.db.tables.Accounts;
import com.cockroachlabs.example.jooq.db.tables.records.AccountsRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountsRecord> ACCOUNTS__PRIMARY = Internal.createUniqueKey(Accounts.ACCOUNTS, DSL.name("primary"), new TableField[] { Accounts.ACCOUNTS.ID }, true);
}
